### ISSUE TITLE
Corrupt files generate 6 error lines with service.resize.images.php

### ISSUE THREAD

**Issue by ervee** [robertvandenbaar/LDG#1]
Hi,

Great, great, great software! Just what I needed to replace https://github.com/jbyers/scry :)

I noticed running the service.resize.images.php generates a lot of errors when it encounters a possibly corrupt file like this:

```
Could not create cropped image Not a JPEG file: starts with 0x33 0x1a `/media/Photos/2005/20050506-0702 UITZOEKEN!!!/PICT0328.JPG' @ error/jpeg.c/JPEGErrorHandler/316
PHP Warning:  Division by zero in /srv/www/htdocs/functions.php on line 197
PHP Warning:  Division by zero in /srv/www/htdocs/functions.php on line 198
PHP Warning:  Division by zero in /srv/www/htdocs/functions.php on line 208
PHP Warning:  Division by zero in /srv/www/htdocs/functions.php on line 208
Could not create resized image Not a JPEG file: starts with 0x33 0x1a `/media/Photos/2005/20050506-0702 UITZOEKEN!!!/PICT0328.JPG' @ error/jpeg.c/JPEGErrorHandler/316
```

That's just for one corrupt file. I seem to have some more :)

My suggestion is to generate only one log line per corrupt file.

Thanks!

**Comment by ervee** [comment]
Also, when I view this folder with LDG it says "Generating 22 thumbnails in the background ..." forever. Probably because the thumbs are never generated on the fly successfully.

**Comment by robertvandenbaar** [comment]
I've made some improvements to the image resizing methods. I've also made sure there will be no attempt at creating a mid-sized image when the thumbnail has already failed. 
I've also made sure the generating on thumbnails (on the fly) doesn't get interrupted when one image fails.
It might come in handy to display a log of files that failed loading/converting. I'll put that on my TODO list ;)

**Comment by ervee** [comment]
Nice! The message is gone, but there is still an issue with this. All thumbnails that it fails to generate do have a placeholder in the thumbnail view.

![capture](https://cloud.githubusercontent.com/assets/4435930/15025902/e064f440-123b-11e6-82f9-6427b3d51fb5.JPG)

Here it fails a lot of thumbnails (corrupted files) so there is a gap up to the last image which is not  currupt.

**Comment by robertvandenbaar** [comment]
Hmm, image corruption is not that common, but it's still an issue! There are 2 ways to deal with this, show a different placeholder (with a title attribute so you can see which image it concerns) or just remove the element from the DOM/page. The former is the best solution I guess.

**Comment by ervee** [comment]
Removing the element would be cleaner. Though I think there should be _some_ indication to the users that a/some thumbnail(s) failed to generate don't you think?

**Comment by robertvandenbaar** [comment]
Showing the user that 'some' of the images failed is not enough information. Showing information about all the images that failed would be too much information I guess (where should we put that).
By showing a placeholder image the user will now which file it concerns. On the other hand it would mean the broken image will still show up in the gallery, but that can be fixed as well.

**Comment by ervee** [comment]
> Showing the user that 'some' of the images failed is not enough information.
Agreed

> Showing information about all the images that failed would be too much information I guess (where should we put that).
At the same place you show the generation progress (after the folder path) you could show a little message "22 thumbnails failed" with a mouse-over action which shows the filenames? Or if you click on it, show the filenames in a pop-up (not a real pop-up, but an in-page pop-up).

> By showing a placeholder image the user will know which file it concerns. On the other hand it would mean the broken image will still show up in the gallery, but that can be fixed as well.
That I can't folow. Show a placeholder and then fix that so it doesn't show up in the gallery? You mean show a placeholder thumbnail, but skip the image when viewing in resized/fullsized mode?

**Comment by robertvandenbaar** [comment]
To answer your last question, yes.

But I've gone with you solution anyway.

**Comment by ervee** [comment]
Looks great to me, thanks! I promise to buy you a beer sometime.
