### ISSUE TITLE
service.resize.images.php stopped working

### ISSUE THREAD

**Issue by ervee** [robertvandenbaar/LDG#3]
Hi!

I moved my LDG installation from a host running Debian 7 to another host running Debian 8 and now my thumbnail cache is not pre-populated anymore :(

When I run the service.resize.images.php manually I see this error:
```
sudo -u www-data php -f /path_to_LDG_installation/service.resize.images.php 2>&1
[...snip...]
Updating thumbnail and mid-size image for /path_to_pictures/PICT0328.JPG
PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x33 0x1a in /path_to_LDG_installation/functions.php on line 29

```
On Debian 7 the scrips also threw some errors but always continued to the end. It would show an error like this:
```Could not create cropped image Not a JPEG file: starts with 0x33 0x1a `/path_to_pictures/PICT0328.JPG' @ error/jpeg.c/JPEGErrorHandler/316```
Now on Debian 8 it just stops when it encounters this file. Is this a difference in PHP, GD or something else? Here's some version info:
Debian 7 php: 5.4.45-0+deb7u5
Debian 7 php-gd: 5.4.45-0+deb7u5
Debian 7 php-imagick: 3.1.0~rc1-1+b2
Debian 8 php-common: 5.6.27+dfsg-0+deb8u1
Debian 8 php-gd: 5.6.27+dfsg-0+deb8u1
Debian 8 php-imagick: Not installed.
Hmm, just might have found something here... Installing php-imagick (argh! 80+MB) and now it works again :)

So it fails with GD when there is no imagick installed :D

**Comment by robertvandenbaar** [comment]
If Imagick is not installed it will fall back to GD. I've made some changes regarding error handling. Not sure if that fixes anything. I haven't been able to reproduce the issue.

**Comment by ervee** [comment]
Thanks! I'll give it a whirl asap and let you know.

**Comment by ervee** [comment]
Nope, didn't fix it. Only the line number in the error changed :P
```PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x33 0x1a in /path_to_LDG_installation/functions.php on line 31```

**Comment by robertvandenbaar** [comment]
I was afraid of that.. I will add an extra check too see if the image is
indeed a jpeg (and not another format). I do however find it odd that GD
triggers a fatal error for this.

I will notify you when I have implemented this change.

Op 6 nov. 2016 21:25 schreef "Ralf" <notifications@github.com>:

**Comment by robertvandenbaar** [comment]
I've committed some changes yesterday (code could use some improvement) but this should fix your issue. Let me know if this works.

**Comment by ervee** [comment]
Looks fixed. I now only get some stderr output like this:
```The contents of file "/path_to_images/PICT0328.JPG" does not match the file extension```
And then just continues.

Thank you!
