### ISSUE TITLE
[Feature request] Filename on mouse-over (or something)

### ISSUE THREAD

**Issue by ervee** [robertvandenbaar/LDG#5]
Hi!

Would it be possible to implement some sort of "show filename on mouse-over" effect?

![ldg-request](https://user-images.githubusercontent.com/4435930/31222608-f75b4954-a9c7-11e7-8cd7-fc9d84467190.jpg)

This would also be helpful on Mobile, but you don't have a mouse there so how would you do that?

**Comment by robertvandenbaar** [comment]
I've added the title attribute on the image, when hovering over it it will show the file name.

**Comment by robertvandenbaar** [comment]
A solution for mobile might get implemented in the feature ;)
