### ISSUE TITLE
Blurry thumbnails

### ISSUE THREAD

**Issue by ervee** [robertvandenbaar/LDG#8]
Hi,

I notice that all generated thumbnails are a but blurred or vague. When I inspect the image info I see the following:
120px × 80px (scaled to 149px × 99px)

I don't think that is wanted behavior?

Thanks for the awesome gallery by the way!

Ralf.

**Comment by robertvandenbaar** [comment]
I have changed the default thumbnail size.

**Comment by ervee** [comment]
It now says:
200px × 130px (scaled to 149px × 97px)
And it looks much better. Still, I'm not a fan of images being resized by the browser. Is there no say to always show the thumbnails the site they are generated? Or is that unwise?

**Comment by robertvandenbaar** [comment]
You always want to display a certain number of images on a row. Every image will be given a certain percentage so it will be equally devided. As long as the image quality is decent/good I'm happy because it will give a good representation of the image.
