### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by postmeee** [robertvandenbaar/LDG#9]
Hello,
First of all thank you for this nice software. I have a problem with the software. Since the number of photos in the directory is over 50000, it becomes impossible to use because there is no pagination in the lists. How do we add pagination on all pages and search results?
cheers

**Comment by robertvandenbaar** [comment]
Hi,

Thanks for your comment! 

I've been meaning to add pagination, particularly on the search result page. On the other pages I don't have the issue because it's organized in folders in such a way that the number of images doesn't get that high, but once I've added it for the search results page it won't be that much work to include it on all pages.

I will keep you posted.

By the way, I was curious as to how you found this software.

Cheers,
Robert

**Comment by postmeee** [comment]
I found this sweet software searcing on github. Tüm photo gallery yazılımlarını inceledim. github'da, bunun kadar pratik ve kullanımı kolay bir yazılım yok . Tam istediğim script. Tek sıkıntı dediğim gibi listeleme sayfalarının ve arama sonuçlarının kısıtlanması konusu. Bu özellik olsaydı, scriptin hiçbir eksiği yok denebilir. Bu şekilde basit ama etkili yazılımları çok seviyorum. 

Bu arada benim dizinlerin altında oldukça fazla sayıda fotoğraf mevcut. Coder değilim ancak ufak tefek şeyleri halledebiliyorum. Kendim yapabilirmiyim diye baktım ancak yazdığınız kodlar biraz karmaşık geldi. Özellikle twig vs gibi  bilmediğim araçları kullanmış olmanız, bunu kendim yapabilmemi engelledi. 

Hızlı cevaın için çok teşekkür ederim... Tahminen bununla ilgilenmen ve özelliğin eklenmesi ne kadar sürer? Kendi işlerimi planlama açısından sordum.
cheers

**Comment by postmeee** [comment]
I found this sweet software searcing on github. I have reviewed all photo gallery software. There is no such practical and easy-to-use software on github. Just the script I want. The only problem, as I said, is the restriction of listing pages and search results. If this feature was present, the script could be said to have no shortcomings. I love simple but effective software in this way.

By the way, I have quite a few photos under my directories. I'm not a Coder, but I can handle small things. I thought I could do it myself, but the code you wrote was a bit complicated. Especially the use of unfamiliar tools such as twig, etc., prevented me to do it myself.

Thank you very much for your quick reply ... How long does it take you to take care of it and add the feature? I asked for planning my own business.

**Comment by robertvandenbaar** [comment]
I've already started working on it and it's mostly implemented. I've been tweaking the default number of pages (is now 200, pages still load well then). If you get many pages in the paginator you probably aren't dividing your images in folders properly and for the search page you should probably enter more words to narrow down the results. 

You can change the number of results per page in the settings.json file.

Give it a try.

**Comment by postmeee** [comment]
dear robert,
This is exactly what I want. thank you very very much. all the best.

**Comment by postmeee** [comment]
hi robert,
if I check the "search in file path" on search box, pagination is not working properly. Second and next pages are not showing.

**Comment by robertvandenbaar** [comment]
The query parameter for "in file path" got lost in the pagination URL's. Fixed.
